sudo: required
language: node_js
node_js:
  - "4.5.0"
env:
  global:
  - CXX=g++-4.8
  - COVERALLS_SERVICE_NAME=travis-ci
    # COVERALLS_REPO_TOKEN (encrypted)
  - secure: RGK5sDRrqz3CcbApcQn0NtYYTTWv1JIbqLzWRAzFA8H3MGaWh+whU+g+SVFAHWUnI4AZzet2Co5RXhA7sJp1ONtsCXatddxmLsh8ZwiEcGtglpEszh4VGZOXQ/6d2ZUZhz8n3RTCoS0VrW7bMbhdHqpOnAX9LO7vL24pGGIbCPoGLWtvHlz3SNZNznZSONM7mp4UePB3UPVD3YkUMrQAWYjguHoI/dV4Cw4bUF8Qvv+mM7YVaqrs77I4o5DuyhtQBYr3pQPdHTX/K55c9MzUd1z4YBgIypxcYRJNPA0vHdkVB/bRWkHL3ygv2uA7A2ISs5YnHCF+j5E0INcKrNv4xG/Z74UffKXiAAWlwS/lU+/xx2QGO++BBfAGkBeCs9D/Ys5fLz7WuIKrHKMUDZIyCzacJJb3jRdW9+eec9RPNVN23f4/sav5VuJp9KaYpCMvhppk8Yavw0J0fKvmTcpLBkscu6o7pdcPOBCHRxNWENRyRdm/demq8VXyp7/+/gPSV5C7pKpg9X4/2QEXI+ABExrvg28UeA3MqzHXX7BiPTv2jGV7TWsUQShXeHSXdstVccP+wfLa83nBQsuvvHC1dNagi/GdBIjk/AmHyr1p2Y6ws3Zz3gozC+XwXp5e6B9Cl2cqM1WLCMlhlr5esSIUO15EsZ1gwGntkhBzkzoCTY0=
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8

install:
- sudo unlink /usr/bin/g++
- sudo ln -s /usr/bin/g++-4.8 /usr/bin/g++
- npm install -g npm
- npm install
- npm install -g grunt-cli
- grunt test
- grunt lint

after_success:
- grunt coverage-report; grunt coveralls
