FROM centos
RUN  yum install -y epel-release; yum install -y git python-pip  python-dev rpm-build redhat-rpm-config
RUN pip install http://repositories.lab.fiware.org/repo/files/fiware-repositories-uploadPkg-1.1.0.tar.gz 
RUN git clone https://github.com/telefonicaid/fiware-aiakos -b develop /opt/fiware-aiakos
WORKDIR /opt/fiware-aiakos
COPY start_rpm.sh start.sh
CMD ./start.sh

