FROM centos
WORKDIR /opt
RUN yum -y install git
RUN curl --silent --location https://rpm.nodesource.com/setup | bash -
RUN yum -y install nodejs
RUN yum -y install rpm-build
RUN yum -y install initscripts
RUN yum -y install crontabs
RUN yum -y install epel-release
RUN yum -y install python-pip python-dev
RUN git clone https://github.com/telefonicaid/fiware-aiakos -b develop /opt/fiware-aiakos
WORKDIR /opt/fiware-aiakos
RUN pip install http://repositories.lab.fiware.org/repo/files/fiware-repositories-uploadPkg-1.1.0.tar.gz 
COPY start.sh start.sh
CMD ./start.sh

