#----------------------------------------------------------------------------
# Aiakos application section (mandatory)
#----------------------------------------------------------------------------
app:
  port: 3000		# App listen port

#-----------------------------------------------------------------------------
#  openstack admin (mandatory)
#-----------------------------------------------------------------------------
openstack:
  username: ''		# admin openstack user
  password: ''		# admin openstack password
